/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dcd9db",
        "surface": "#fcf8fa",
        "surface-bright": "#fcf8fa",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#574425",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e3fd",
        "outline": "#76777d",
        "primary-fixed": "#dae2fd",
        "surface-variant": "#e4e2e4",
        "surface-container-high": "#eae7e9",
        "on-secondary-container": "#57657b",
        "inverse-surface": "#303032",
        "background": "#fcf8fa",
        "surface-tint": "#565e74",
        "error": "#ba1a1a",
        "tertiary": "#000000",
        "surface-container-highest": "#e4e2e4",
        "on-primary-fixed": "#131b2e",
        "secondary-fixed": "#d5e3fd",
        "surface-container": "#f0edef",
        "secondary-fixed-dim": "#b9c7e0",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#7c839b",
        "tertiary-container": "#271901",
        "on-secondary-fixed": "#0d1c2f",
        "on-surface": "#1b1b1d",
        "primary-container": "#131b2e",
        "on-tertiary-container": "#98805d",
        "tertiary-fixed-dim": "#dec29a",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary": "#000000",
        "on-surface-variant": "#45464d",
        "inverse-primary": "#bec6e0",
        "secondary": "#515f74",
        "inverse-on-surface": "#f3f0f2",
        "on-secondary-fixed-variant": "#3a485c",
        "tertiary-fixed": "#fcdeb5",
        "on-tertiary-fixed": "#271901",
        "surface-container-low": "#f6f3f5",
        "outline-variant": "#c6c6cd",
        "on-background": "#1b1b1d",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "slate-950": "#0f172a"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-gap": "16px",
        "sidebar-width": "260px",
        "base": "4px",
        "grid-gutter": "20px",
        "container-padding": "24px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}